name: Deploy to Firebase Hosting (main)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    permissions: { contents: read }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Write service account JSON to a file
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$RUNNER_TEMP/firebase-sa.json"
          printf '%s' "$FIREBASE_SERVICE_ACCOUNT" > "$GOOGLE_APPLICATION_CREDENTIALS"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> $GITHUB_ENV

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_PROJECT: true-vape-reviews-c5399            # <-- put your project ID
        run: |
          firebase deploy --only hosting --project "$FIREBASE_PROJECT" --non-interactive
